#!/bin/bash

dir=$1
arr=($(find $dir -maxdepth 1 -type f | sort))
len=${#arr[@]}

for (( i=0; i<$len; i++))
do
	for (( j=$i+1; j<$len; j++))
	do
		if cmp -s "${arr[$i]}" "${arr[$j]}"
		then 
			ln -f "${arr[$i]}" "${arr[$j]}"
		fi
	done
done	
				
